#!/usr/bin/python
import pyvisa as visa
import time
from time import process_time
t_start = time.time()
print(t_start)
resources = visa.ResourceManager('@py')
print(resources.list_resources())
siggen = resources.open_resource('USB0::1689::835::C021191::0::INSTR')
print(siggen.query('*IDN?'))
print(siggen.write('*RST'))
siggen.read_termination = '\n'
siggen.write_termination = '\n'
time.sleep(0.05)
#print(siggen.write(':;:;:;:;:;:;:;:;:;: ;:'))
print(siggen.write('SOUR1:FUNC:SHAPE PULSE'))
time.sleep(0.05)
print(siggen.write('SOUR1:BURS:STATE ON'))
time.sleep(0.05)
print(siggen.write('SOUR1:BURS:NCYC 10000'))
time.sleep(0.05)
print(siggen.write('SOUR1:VOLT:IMM:OFFS 0.01'))
time.sleep(0.05)
print(siggen.write('SOUR1:FREQ:FIX 100kHz'))
time.sleep(0.05)
print(siggen.write('SOUR1:PULS:TRAN:TRA 1515ns'))
time.sleep(0.05)
print(siggen.write('SOUR1:PULS:TRAN:LEAD 5ns'))
time.sleep(0.05)
print(siggen.write('SOUR1:PULS:WIDT 950ns'))
time.sleep(0.05)
print(siggen.write('SOUR1:PULS:DEL 7000ns'))
time.sleep(0.05)
print(siggen.write('TRIG:SEQ:SOUR EXT'))
#time.sleep(0.05)
#print(siggen.write('TRIG:SEQ:TIM 1ms'))
time.sleep(0.05)
print(siggen.write('SOUR1:VOLT:LEV:IMM:LOW 38mV'))
time.sleep(0.05)
print(siggen.write('SOUR1:VOLT:LEV:IMM:HIGH 75mV'))
time.sleep(0.05)
print(siggen.write('SOUR1:BURS:TDEL 25ms'))
time.sleep(0.05)
print(siggen.write('OUTP1:POL INV'))
time.sleep(0.05)
print(siggen.write('SOUR2:FUNC:SHAPE SQUARE'))
time.sleep(0.05)
print(siggen.write('SOUR2:BURS:STATE ON'))
time.sleep(0.05)
print(siggen.write('SOUR2:BURS:NCYC 1'))
time.sleep(0.05)
print(siggen.write('SOUR2:VOLT:LEV:IMM:AMPL 1.8'))
time.sleep(0.05)
print(siggen.write('SOUR2:VOLT:IMM:OFFS 0.9'))
time.sleep(0.05)


print(siggen.write('OUTP1:STAT ON'))
time.sleep(0.1)
siggen.write('TRIG:IMM')
time.sleep(0.2)
print(siggen.write('OUTP2:STAT ON'))
time.sleep(0.1)
for i in range(1,128):
    print(i)
    print(siggen.write('TRIG:IMM'))
    time.sleep(0.13)
#    print(siggen.write('OUTP1:STAT OFF'))
#    time.sleep(0.05)
#    print(siggen.write('OUTP2:STAT ON'))
#    time.sleep(0.05)
#    print(siggen.write('TRIG:IMM'))
#    time.sleep(0.05)
#    print(siggen.write('OUTP2:STAT OFF'))
#    time.sleep(0.05)
#    print(siggen.write('OUTP1:STAT ON'))
#    time.sleep(0.05)
print(siggen.write('OUTP1:STAT OFF'))
print(siggen.write('OUTP2:STAT OFF'))
#time.sleep(0.05)
t_stop = time.time()
t_elapsed = t_stop-t_start
print("Time elapsed: ",t_elapsed)
print(siggen.write('SYST:BEEP:IMM'))
